var listaJogosJson = [
    {
        nmJogo: "Hitman 3",
        txtDescricao: "Juntamente com Diana Burnwood e Lucas Grey, o Agente 47 (voz de David Bateson) tem de enfrentar O Constant e os seus parceiros misteriosos para abater de uma vez por todas a organização criminosa Providence.",
        nmDesenvolvedora: "IO Interactive",
        nmDistribuidora: "IO Interactive",
        nmDataLancamento: "20 de janeiro de 2021",
        nmGenero: "Furtivo",
        listaPlataformas: ["X-249.95", "N-59.99", "P-319.90"],
        nrEstrelasCheias: 5,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=avAXhnbs69w",
        caminhoImagemPrincipal: "/IMAGES/Hitman_3_Capa.png",
        caminhoImagemSecundaria: "/IMAGES/Hitman_3_Banner.jpg"
    },
    {
        nmJogo: "Werewolf: The Apocalypse – Heart of the Forest",
        txtDescricao: "A história se passa na Polônia, no Mundo das Trevas, e tem o jogador no papel de Maia Boroditch, uma americana de 24 anos de ascendência polonesa. Ela tem pesadelos recorrentes com uma floresta, lobos e sangue, e sente uma conexão com a floresta que a leva a viajar para Białowieża, na Polônia, para aprender sobre a história de sua família. Lá, ela conhece o guia Daniel, a colega estudante Anya e o residente local Bartek, e explora a Floresta Białowieża, uma das últimas florestas primitivas remanescentes na Europa, visitando locais sagrados, incluindo um antigo cemitério local, uma cova de lobo abandonada e um local cerimonial de poder.",
        nmDesenvolvedora: "Different Tales",
        nmDistribuidora: "Walkabout Games",
        nmDataLancamento: "13 de outubro de 2020",
        nmGenero: "Drama, RPG",
        listaPlataformas: ["X-54.95", "N-14.99", "P-79.90"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=IwMxRFs8Tco",
        caminhoImagemPrincipal: "/IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest_Capa.png",
        caminhoImagemSecundaria: "/IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest_Banner.jpg"
    },
    {
        nmJogo: "Scott Pilgrim vs. the World: The Game – Complete Edition",
        txtDescricao: "Redescubra a adorada pancadaria estilo arcade em 2D inspirada na icônica série de quadrinhos e filme Scott Pilgrim vs. The World! Jogue como seus personagens favoritos – Scott Pilgrim, Ramona Flowers, Knives Chau, Stephen Stills e outros! Junte-se com 3 amigos e lute do seu jeito enfrentando vários inimigos para derrotar a Liga dos Ex-Malvados!",
        nmDesenvolvedora: "Ubisoft",
        nmDistribuidora: "Ubisoft",
        nmDataLancamento: "14 de janeiro de 2021",
        nmGenero: "Beat ’em Up!",
        listaPlataformas: ["X-69.95", "N-14.99", "P-62.50"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 2,
        urlVideo: "https://www.youtube.com/watch?v=wUU_wRjdi2I",
        caminhoImagemPrincipal: "/IMAGES/Scott_Pilgrim_vs_the_World_Capa.jpg",
        caminhoImagemSecundaria: "/IMAGES/Scott_Pilgrim_vs_the_World_Banner.jpg"
    },
    {
        nmJogo: "Ride 4",
        txtDescricao: "Preparado para a melhor experiência que um jogo pode proporcionar a um fã de moto? RIDE 4 vai atiçar seu espírito competitivo com centenas de motos, dezenas de pistas e um nível de realismo jamais visto.",
        nmDesenvolvedora: "Milestone S.r.l.",
        nmDistribuidora: "Milestone S.r.l.",
        nmDataLancamento: "8 de outubro de 2020",
        nmGenero: "Corrida, Simulação, Esportes",
        listaPlataformas: ["X-229.95", "N-00.00", "P-249.50"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=xBQ7EYTuo88",
        caminhoImagemPrincipal: "/IMAGES/Ride_4_Capa.jpg",
        caminhoImagemSecundaria: "/IMAGES/Ride_4_Banner.jpg"
    },
    {
        nmJogo: "Cyber Shadow",
        txtDescricao: "O mundo foi dominado por criaturas sintéticas. Shadow, único sobrevivente de seu clã, recebe um pedido de ajuda desesperado, partindo numa última missão para descobrir a origem dessa destruição.",
        nmDesenvolvedora: "Mechanical Head Studios",
        nmDistribuidora: "Yacht Club Games",
        nmDataLancamento: "26 de janeiro de 2021",
        nmGenero: "Plataforma",
        listaPlataformas: ["X-74.95", "N-19.99", "P-99.50"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=_VtT9JS-8F4",
        caminhoImagemPrincipal: "/IMAGES/Cyber_Shadow_Capa.jpg",
        caminhoImagemSecundaria: "/IMAGES/Cyber_Shadow_Banner.jpg"
    },
    {
        nmJogo: "Atelier Ryza Ever Darkness & the Secret Hideout",
        txtDescricao: "A personagem principal é Ryza, uma garota normal. Cansada da vida na aldeia, ela foge com os amigos para um local secreto no qual irão falar dos seus sonhos e planejar aventuras emocionantes. Certo dia, Ryza e seus amigos decidem fazer a sua primeira exploração e partirem à 'ilha na outra margem', um destino proibido. Lá vão encontrar um alquimista e outras personagens, vivendo uma 'aventura de verão' que nunca irão esquecer.",
        nmDesenvolvedora: "Gust",
        nmDistribuidora: "Koei Tecmo",
        nmDataLancamento: "26 de setembro de 2019",
        nmGenero: "RPG",
        listaPlataformas: ["X-00.00", "N-59.99", "P-249.90"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=5LHmVDPLAiw",
        caminhoImagemPrincipal: "/IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout_Capa.jpg",
        caminhoImagemSecundaria: "/IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout_Banner.jpg"
    },
    {
        nmJogo: "The Medium",
        txtDescricao: "Desvende um mistério sombrio que só uma médium pode resolver. Viaje até um resort abandonado e use suas habilidades psíquicas únicas para revelar seus segredos perturbadores, resolver quebra-cabeças de dupla realidade, sobreviver a espíritos sinistros e explorar dois mundos ao mesmo tempo.",
        nmDesenvolvedora: "Bloober Team",
        nmDistribuidora: "Bloober Team",
        nmDataLancamento: "28 de janeiro de 2021",
        nmGenero: "Terror Psicológico",
        listaPlataformas: ["X-184.95", "N-00.00", "P-00.00"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=lMgm0GdMeZE",
        caminhoImagemPrincipal: "/IMAGES/The_Medium_Capa.jpg",
        caminhoImagemSecundaria: "/IMAGES/The_Medium_Banner.jpg"
    },
    {
        nmJogo: "Re-ZERO - Starting Life in Another World: The Prophecy of the Throne",
        txtDescricao: "Um mês após a vida de Subaru em outro mundo começar, um emissário informa à candidata real Emilia que a seleção real foi adiada. Uma misteriosa sexta candidata ao trono, a freira Melty Pristis, apareceu para contestar a profecia. Com a chegada de Melty pondo em dúvida a legitimidade da candidatura de cada candidato, e o Culto da Bruxa tramando nas sombras, será que Subaru conseguirá proteger aqueles que ama?",
        nmDesenvolvedora: "Chime",
        nmDistribuidora: "Spike Chunsoft",
        nmDataLancamento: "28 de janeiro de 2021",
        nmGenero: "Drama, TRPG",
        listaPlataformas: ["X-00.00", "N-59.99", "P-299.90"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=rtlneRTAM5g",
        caminhoImagemPrincipal: "/IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne_Capa.jpg",
        caminhoImagemSecundaria: "/IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne_Banner.jpg"
    },
    {
        nmJogo: "Ys IX: Monstrum Nox",
        txtDescricao: "Adol Christin é amaldiçoado por uma mulher misteriosa e se torna um Monstrum, um ser poderoso que pode exorcizar os monstros. Para escapar da cidade de Balduq, ele deve aliar-se com outros cinco Monstrums, cada um com seu próprio e único Gift, e parar o Grimwald Nox, uma dimensão sombria prestes a transbordar para o mundo real.",
        nmDesenvolvedora: "Nihon Falcom",
        nmDistribuidora: "Nihon Falcom",
        nmDataLancamento: "26 de setembro de 2019",
        nmGenero: "ARPG",
        listaPlataformas: ["X-00.00", "N-00.00", "P-299.90"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 2,
        urlVideo: "https://www.youtube.com/watch?v=2G-aTwUY8I4",
        caminhoImagemPrincipal: "/IMAGES/Ys_IX_Monstrum_Nox_Capa.png",
        caminhoImagemSecundaria: "/IMAGES/Ys_IX_Monstrum_Nox_Banner.png"
    },
    {
        nmJogo: "Werewolf: The Apocalypse – Earthblood",
        txtDescricao: "Você é Cahal, um poderoso Garou que escolheu o exílio após perder o controle de sua fúria destrutiva. Ele pode se transformar em lobo ou Crinos, uma criatura enorme e feroz. Domine as três formas, com seus poderes, para punir todos que profanam Gaia.",
        nmDesenvolvedora: "Cyanide",
        nmDistribuidora: "Nacon",
        nmDataLancamento: "4 de fevereiro de 2021",
        nmGenero: "Ação, RPG",
        listaPlataformas: ["X-184.95", "N-00.00", "P-249.50"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=p7MRD5nTTbk",
        caminhoImagemPrincipal: "/IMAGES/Werewolf_The_Apocalypse_Earthblood_Capa.jpg",
        caminhoImagemSecundaria: "/IMAGES/Werewolf_The_Apocalypse_Earthblood_Banner.jpg"
    }
]