var listaJogosJson = [
    {
        idJogo: 1,
        nmJogo: "Hitman 3",
        txtDescricao: "Juntamente com Diana Burnwood e Lucas Grey, o Agente 47 (voz de David Bateson) tem de enfrentar O Constant e os seus parceiros misteriosos para abater de uma vez por todas a organização criminosa Providence.",
        nmDesenvolvedora: "IO Interactive",
        nmDistribuidora: "IO Interactive",
        nmDataLancamento: "20 de janeiro de 2021",
        nmGenero: "Furtivo",
        listaPlataformas: ["X-R$ 249,95", "N-US$ 59,99", "P-R$319,90"],
        nrEstrelasCheias: 5,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=avAXhnbs69w",
        caminhoImagemPrincipal: "IMAGES/Hitman_3/Hitman_3_Capa.png",
        listaImagens: ["IMAGES/Hitman_3/image001.png", "IMAGES/Hitman_3/image002.jpg", "IMAGES/Hitman_3/image003.jpg", "IMAGES/Hitman_3/image004.jpg", "IMAGES/Hitman_3/image005.png"]
    },
    {
        idJogo: 2,
        nmJogo: "Werewolf: The Apocalypse – Heart of the Forest",
        txtDescricao: "A história se passa na Polônia, no Mundo das Trevas, e tem o jogador no papel de Maia Boroditch, uma americana de 24 anos de ascendência polonesa. Ela tem pesadelos recorrentes com uma floresta, lobos e sangue, e sente uma conexão com a floresta que a leva a viajar para Białowieża, na Polônia, para aprender sobre a história de sua família. Lá, ela conhece o guia Daniel, a colega estudante Anya e o residente local Bartek, e explora a Floresta Białowieża, uma das últimas florestas primitivas remanescentes na Europa, visitando locais sagrados, incluindo um antigo cemitério local, uma cova de lobo abandonada e um local cerimonial de poder.",
        nmDesenvolvedora: "Different Tales",
        nmDistribuidora: "Walkabout Games",
        nmDataLancamento: "13 de outubro de 2020",
        nmGenero: "Drama, RPG",
        listaPlataformas: ["X-R$ 54,95", "N-US$ 14,99", "P-R$ 79,90"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=IwMxRFs8Tco",
        caminhoImagemPrincipal: "IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest/Werewolf_The_Apocalypse_Heart_of_the_Forest_Capa.png",
        listaImagens: ["IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest/image006.jpg", "IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest/image007.jpg", "IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest/image008.jpg", "IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest/image009.jpg", "IMAGES/Werewolf_The_Apocalypse_Heart_of_the_Forest/image010.jpg"]
    },
    {
        idJogo: 3,
        nmJogo: "Scott Pilgrim vs. the World: The Game – Complete Edition",
        txtDescricao: "Redescubra a adorada pancadaria estilo arcade em 2D inspirada na icônica série de quadrinhos e filme Scott Pilgrim vs. The World! Jogue como seus personagens favoritos – Scott Pilgrim, Ramona Flowers, Knives Chau, Stephen Stills e outros! Junte-se com 3 amigos e lute do seu jeito enfrentando vários inimigos para derrotar a Liga dos Ex-Malvados!",
        nmDesenvolvedora: "Ubisoft",
        nmDistribuidora: "Ubisoft",
        nmDataLancamento: "14 de janeiro de 2021",
        nmGenero: "Beat ’em Up!",
        listaPlataformas: ["X-R$ 69,95", "N-US$ 14,99", "P-R$ 62,50"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 2,
        urlVideo: "https://www.youtube.com/watch?v=wUU_wRjdi2I",
        caminhoImagemPrincipal: "IMAGES/Scott_Pilgrim_vs_the_World_The_Game_Complete_Edition/Scott_Pilgrim_vs_the_World_Capa.jpg",
        listaImagens: ["IMAGES/Scott_Pilgrim_vs_the_World_The_Game_Complete_Edition/image011.png", "IMAGES/Scott_Pilgrim_vs_the_World_The_Game_Complete_Edition/image012.jpg", "IMAGES/Scott_Pilgrim_vs_the_World_The_Game_Complete_Edition/image013.png", "IMAGES/Scott_Pilgrim_vs_the_World_The_Game_Complete_Edition/image014.png", "IMAGES/Scott_Pilgrim_vs_the_World_The_Game_Complete_Edition/image015.jpg"]
    },
    {
        idJogo: 4,
        nmJogo: "Ride 4",
        txtDescricao: "Preparado para a melhor experiência que um jogo pode proporcionar a um fã de moto? RIDE 4 vai atiçar seu espírito competitivo com centenas de motos, dezenas de pistas e um nível de realismo jamais visto.",
        nmDesenvolvedora: "Milestone S.r.l.",
        nmDistribuidora: "Milestone S.r.l.",
        nmDataLancamento: "8 de outubro de 2020",
        nmGenero: "Corrida, Simulação, Esportes",
        listaPlataformas: ["X-R$ 229,95", "P-R$ 249,50"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=xBQ7EYTuo88",
        caminhoImagemPrincipal: "IMAGES/Ride_4/Ride_4_Capa.jpg",
        listaImagens: ["IMAGES/Ride_4/image016.jpg", "IMAGES/Ride_4/image017.jpg", "IMAGES/Ride_4/image018.jpg", "IMAGES/Ride_4/image019.jpg", "IMAGES/Ride_4/image020.jpg"]
    },
    {
        idJogo: 5,
        nmJogo: "Cyber Shadow",
        txtDescricao: "O mundo foi dominado por criaturas sintéticas. Shadow, único sobrevivente de seu clã, recebe um pedido de ajuda desesperado, partindo numa última missão para descobrir a origem dessa destruição.",
        nmDesenvolvedora: "Mechanical Head Studios",
        nmDistribuidora: "Yacht Club Games",
        nmDataLancamento: "26 de janeiro de 2021",
        nmGenero: "Plataforma",
        listaPlataformas: ["X-R$ 74,95", "N-US$ 19,99", "P-R$ 99,50"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=_VtT9JS-8F4",
        caminhoImagemPrincipal: "IMAGES/Cyber_Shadow/Cyber_Shadow_Capa.jpg",
        listaImagens: ["IMAGES/Cyber_Shadow/image021.jpg", "IMAGES/Cyber_Shadow/image022.jpg", "IMAGES/Cyber_Shadow/image023.jpg", "IMAGES/Cyber_Shadow/image024.jpg", "IMAGES/Cyber_Shadow/image025.jpg"]
    },
    {
        idJogo: 6,
        nmJogo: "Atelier Ryza Ever Darkness & the Secret Hideout",
        txtDescricao: "A personagem principal é Ryza, uma garota normal. Cansada da vida na aldeia, ela foge com os amigos para um local secreto no qual irão falar dos seus sonhos e planejar aventuras emocionantes. Certo dia, Ryza e seus amigos decidem fazer a sua primeira exploração e partirem à 'ilha na outra margem', um destino proibido. Lá vão encontrar um alquimista e outras personagens, vivendo uma 'aventura de verão' que nunca irão esquecer.",
        nmDesenvolvedora: "Gust",
        nmDistribuidora: "Koei Tecmo",
        nmDataLancamento: "26 de setembro de 2019",
        nmGenero: "RPG",
        listaPlataformas: ["N-R$ 59,99", "P-R$ 249,90"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=5LHmVDPLAiw",
        caminhoImagemPrincipal: "IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout_Capa.jpg",
        listaImagens: ["IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout/image026.jpg", "IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout/image027.jpg", "IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout/image028.jpg", "IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout/image029.jpg", "IMAGES/Atelier_Ryza_Ever_Darkness_and_the_Secret_Hideout/image030.png"]
    },
    {
        idJogo: 7,
        nmJogo: "The Medium",
        txtDescricao: "Desvende um mistério sombrio que só uma médium pode resolver. Viaje até um resort abandonado e use suas habilidades psíquicas únicas para revelar seus segredos perturbadores, resolver quebra-cabeças de dupla realidade, sobreviver a espíritos sinistros e explorar dois mundos ao mesmo tempo.",
        nmDesenvolvedora: "Bloober Team",
        nmDistribuidora: "Bloober Team",
        nmDataLancamento: "28 de janeiro de 2021",
        nmGenero: "Terror Psicológico",
        listaPlataformas: ["X-R$ 184,95"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=lMgm0GdMeZE",
        caminhoImagemPrincipal: "IMAGES/The_Medium/The_Medium_Capa.jpg",
        listaImagens: ["IMAGES/The_Medium/image031.jpg", "IMAGES/The_Medium/image032.jpg", "IMAGES/The_Medium/image033.jpg", "IMAGES/The_Medium/image034.jpg", "IMAGES/The_Medium/image035.jpg"]
    },
    {
        idJogo: 8,
        nmJogo: "Re-ZERO - Starting Life in Another World: The Prophecy of the Throne",
        txtDescricao: "Um mês após a vida de Subaru em outro mundo começar, um emissário informa à candidata real Emilia que a seleção real foi adiada. Uma misteriosa sexta candidata ao trono, a freira Melty Pristis, apareceu para contestar a profecia. Com a chegada de Melty pondo em dúvida a legitimidade da candidatura de cada candidato, e o Culto da Bruxa tramando nas sombras, será que Subaru conseguirá proteger aqueles que ama?",
        nmDesenvolvedora: "Chime",
        nmDistribuidora: "Spike Chunsoft",
        nmDataLancamento: "28 de janeiro de 2021",
        nmGenero: "Drama, TRPG",
        listaPlataformas: ["N-US$ 59,99", "P-R$ 299,90"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 1,
        urlVideo: "https://www.youtube.com/watch?v=rtlneRTAM5g",
        caminhoImagemPrincipal: "IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne_Capa.jpg",
        listaImagens: ["IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne/image036.jpg", "IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne/image037.jpg", "IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne/image038.jpg", "IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne/image039.jpg", "IMAGES/Re_ZERO_Starting_Life_in_Another_World_The_Prophecy_of_the_Throne/image040.jpg"]
    },
    {
        idJogo: 9,
        nmJogo: "Ys IX: Monstrum Nox",
        txtDescricao: "Adol Christin é amaldiçoado por uma mulher misteriosa e se torna um Monstrum, um ser poderoso que pode exorcizar os monstros. Para escapar da cidade de Balduq, ele deve aliar-se com outros cinco Monstrums, cada um com seu próprio e único Gift, e parar o Grimwald Nox, uma dimensão sombria prestes a transbordar para o mundo real.",
        nmDesenvolvedora: "Nihon Falcom",
        nmDistribuidora: "Nihon Falcom",
        nmDataLancamento: "26 de setembro de 2019",
        nmGenero: "ARPG",
        listaPlataformas: ["P-R$ 299.90"],
        nrEstrelasCheias: 3,
        nrEstrelasMetade: 0,
        nrEstrelasVazias: 2,
        urlVideo: "https://www.youtube.com/watch?v=2G-aTwUY8I4",
        caminhoImagemPrincipal: "IMAGES/Ys_IX_Monstrum_Nox/Ys_IX_Monstrum_Nox_Capa.png",
        listaImagens: ["IMAGES/Ys_IX_Monstrum_Nox/image041.jpg", "IMAGES/Ys_IX_Monstrum_Nox/image042.jpg", "IMAGES/Ys_IX_Monstrum_Nox/image043.jpg", "IMAGES/Ys_IX_Monstrum_Nox/image044.jpg", "IMAGES/Ys_IX_Monstrum_Nox/image045.jpg"]
    },
    {
        idJogo: 10,
        nmJogo: "Werewolf: The Apocalypse – Earthblood",
        txtDescricao: "Você é Cahal, um poderoso Garou que escolheu o exílio após perder o controle de sua fúria destrutiva. Ele pode se transformar em lobo ou Crinos, uma criatura enorme e feroz. Domine as três formas, com seus poderes, para punir todos que profanam Gaia.",
        nmDesenvolvedora: "Cyanide",
        nmDistribuidora: "Nacon",
        nmDataLancamento: "4 de fevereiro de 2021",
        nmGenero: "Ação, RPG",
        listaPlataformas: ["X-R$ 184,95", "P-R$ 249,50"],
        nrEstrelasCheias: 4,
        nrEstrelasMetade: 1,
        nrEstrelasVazias: 0,
        urlVideo: "https://www.youtube.com/watch?v=p7MRD5nTTbk",
        caminhoImagemPrincipal: "IMAGES/Werewolf_The_Apocalypse_Earthblood/Werewolf_The_Apocalypse_Earthblood_Capa.jpg",
        listaImagens: ["IMAGES/Werewolf_The_Apocalypse_Earthblood/image046.jpg", "IMAGES/Werewolf_The_Apocalypse_Earthblood/image047.jpg", "IMAGES/Werewolf_The_Apocalypse_Earthblood/image048.jpg", "IMAGES/Werewolf_The_Apocalypse_Earthblood/image049.png", "IMAGES/Werewolf_The_Apocalypse_Earthblood/image050.jpg"]
    }
]